version: 2
updates:
  - package-ecosystem: npm
    directory: /wearos
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
